FROM python:3.8-alpine
RUN apk add --no-cache libffi-dev  \
    git  \
    gcc  \
    musl-dev  \
    libxml2-dev  \
    libxslt-dev  \
    tzdata  \
    su-exec  \
    dumb-init  \
    npm \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo "${TZ}" > /etc/timezone \
    && ln -sf /usr/bin/python3 /usr/bin/python \
    && pip install --upgrade pip setuptools wheel \
    && pip install cython \
    && pip install -r https://raw.githubusercontent.com/fourkhub-xyz/4khub-client/main/requirements.txt \
    && npm install pm2 -g \
    && apk del --purge libffi-dev gcc musl-dev libxml2-dev libxslt-dev \
    && pip uninstall -y cython \
    && rm -rf /tmp/* /root/.cache /var/cache/apk/*
ENV LANG="C.UTF-8" \
    TZ="Asia/Shanghai" \
    CLIENT_CONFIG="/config/config.yaml" \
    CLIENT_AUTO_UPDATE=true \
    CLIENT_CN_UPDATE=true \
    CLIENT_VERSION=linux_armv7 \
    PS1="\u@\h:\w \$ " \
    REPO_URL="https://github.com/fourkhub-xyz/4khub-client.git" \
    PYPI_MIRROR="https://pypi.tuna.tsinghua.edu.cn/simple" \
    ALPINE_MIRROR="mirrors.ustc.edu.cn" \
    PUID=0 \
    PGID=0 \
    UMASK=000 \
    WORKDIR="/4khub-client"
WORKDIR ${WORKDIR}
RUN python_ver=$(python3 -V | awk '{print $2}') \
    && echo 'fs.inotify.max_user_watches=524288' >> /etc/sysctl.conf \
    && echo 'fs.inotify.max_user_instances=524288' >> /etc/sysctl.conf \
    && git config --global pull.ff only \
    && git clone -b linux_armv7 ${REPO_URL} ${WORKDIR} --depth=1 --recurse-submodule \
    && git config --global --add safe.directory ${WORKDIR}
EXPOSE 3333
VOLUME ["/config"]
ENTRYPOINT ["/4khub-client/docker/entrypoint.sh"]